### ISSUE TITLE
Tracking issue for webgpu 0.8 upgrade

### ISSUE THREAD

**Issue by AlexEne** [nannou-org/nannou#734]
I've started an upgrade to 0.8 [here](https://github.com/AlexEne/nannou) and I'm creating this issue to track the progress.
This is not a final list, just what I found so far.

- [x] Wait for conrod to upgrade: https://github.com/PistonDevelopers/conrod/pull/1416
- [X] Upgrade the nannou code-base to wgpu `0.8` (it's here: https://github.com/AlexEne/nannou)
- [x] Fix  IMPLICIT_LEVEL in [27] is not fulfilled because of Expression([3]
- [X] Fix blending options for `Min` and `Max` they should both be using `One`.
- [x] `timeline_demo` fails because of colorable trait not being implemented by the `Timeline`. It seems conrod has added a special trait that you need to have in order to allow people to call `color(...)`

**Comment by AlexEne** [comment]
Running some examples I get: 
```
error: process didn't exit successfully: `target\debug\examples\draw_texture_sampler.exe` (exit code: 0xc000041d)
PS G:\Rust\nannou> cargo run --example draw_blend
   Compiling examples v0.1.0 (G:\Rust\nannou\examples)
    Finished dev [unoptimized + debuginfo] target(s) in 4.99s
     Running `target\debug\examples\draw_blend.exe`
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `nannou_shader_module`
    Function [1] 'main' is invalid
    Required uniformity of control flow for IMPLICIT_LEVEL in [27] is not fulfilled because of Expression([3])
```

**Comment by AlexEne** [comment]
I've fixed that error above by modifying `shader.frag` to not sample a potentially mipmapped texture inside an if block:
```
void main() {
    vec4 f_color_texture = texture(sampler2D(tex, tex_sampler), v_tex_coords);
    float tex_a = texture(sampler2D(text, text_sampler), v_tex_coords).r;
    
    // Color
    if (v_mode == uint(0)) {
        f_color = v_color;
    // Texture
    } else if (v_mode == uint(1)) {
        f_color = f_color_texture;
    // Text
    } else if (v_mode == uint(2)) {
        f_color = vec4(v_color.rgb, v_color.a * tex_a);
    // Unhandled mode - Indicate error with red.
    } else {
        f_color = vec4(1.0, 0.0, 0.0, 1.0);
    }
}
```

The webgpu-rs devs also suggested I would leave inside the if and specify the lod level if I know exactly what level to sample from.

**Comment by AlexEne** [comment]
I've decided to try my luck here with sampling twice because we get textures from people experimenting with the framework so it's probably better to be more generic rather than limit it to `0`.

**Comment by AlexEne** [comment]
Closing this as there's a PR ready to merge: https://github.com/nannou-org/nannou/pull/737
